### ISSUE TITLE
评论

### ISSUE THREAD

**Issue by JohnChiao75** [JohnChiao75/blog#3]
代码：
```yml
comments: 
    use: Valine
```

**Comment by JohnChiao75** [comment]
```yml
valine:
  appId: # leancloud application app id
  appKey: # leancloud application app key
```
